#-------------DYNAMODB-------------------------------
playersTableName: Players
playersSeeder: [./seeds/players.json]

#-------------SNS------------------------------------
scrapingTopicName: scrapingTopic
postPlayerTopicName: postPlayerTopic

#-------------API GATEWAY---------------------------
apiUrls:
  players: players

#----------General Config----------
accountIdNumber: 533796783460
region: eu-west-1
stage: prod