#-------------DYNAMODB-------------------------------
playersTableName: Players
playersSeeder: [./seeds/players.json]

#-------------SNS------------------------------------
scrapingTopicName: scrapingTopic
postPlayerTopicName: postPlayerTopic

#-------------API GATEWAY---------------------------
apiUrls:
  players: players
  scraping: scraping

#----------AccountId----------
accountIdNumber: 533796783460

