--- #-------------DYNAMODB-------------------------------
playersTableName: Players

#-------------S3------------------------------------
rankingBucket: rankingbucket

#-------------SNS------------------------------------
scrapingTopicName: scrapingTopic
postPlayerTopicName: postPlayerTopic
#-------------API GATEWAY---------------------------
apiUrls:
  players: players
  scraping: scraping

#----------AccountId----------
accountIdNumber: 533796783460

